# Generated by Django 4.2 on 2023-05-02 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('paragraph', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
                ('Duration', models.CharField(max_length=250, null=True)),
                ('teacher', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LessonTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curs.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('Duration', models.CharField(max_length=250, null=True)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curs.lessontopic')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=255)),
                ('basecategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basecategory', to='curs.basecategory')),
            ],
        ),
    ]
