# Generated by Django 4.2 on 2023-05-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
